package Util;
// Generated Apr 19, 2024 12:15:48 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Curso generated by hbm2java
 */
public class Curso  implements java.io.Serializable {


     private int id;
     private String nome;
     private Set estudantes = new HashSet(0);

    public Curso() {
    }

	
    public Curso(int id) {
        this.id = id;
    }
    public Curso(int id, String nome, Set estudantes) {
       this.id = id;
       this.nome = nome;
       this.estudantes = estudantes;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set getEstudantes() {
        return this.estudantes;
    }
    
    public void setEstudantes(Set estudantes) {
        this.estudantes = estudantes;
    }




}


