package Util;
// Generated Apr 19, 2024 12:15:48 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Disciplina generated by hbm2java
 */
public class Disciplina  implements java.io.Serializable {


     private int id;
     private String nome;
     private Integer chs;
     private Integer credito;
     private Set avaliacaos = new HashSet(0);

    public Disciplina() {
    }

	
    public Disciplina(int id) {
        this.id = id;
    }
    public Disciplina(int id, String nome, Integer chs, Integer credito, Set avaliacaos) {
       this.id = id;
       this.nome = nome;
       this.chs = chs;
       this.credito = credito;
       this.avaliacaos = avaliacaos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Integer getChs() {
        return this.chs;
    }
    
    public void setChs(Integer chs) {
        this.chs = chs;
    }
    public Integer getCredito() {
        return this.credito;
    }
    
    public void setCredito(Integer credito) {
        this.credito = credito;
    }
    public Set getAvaliacaos() {
        return this.avaliacaos;
    }
    
    public void setAvaliacaos(Set avaliacaos) {
        this.avaliacaos = avaliacaos;
    }




}


